version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stock-market
    ports:
      - "5432:5432"
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:7.4
    restart: always
    ports:
      - "8100:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - local-network

  stock-market:
    image: stock-market
    restart: always
    ports:
      - "8080:8080"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
