version: '3.8'

services:
  postgres:
    image: postgres:16.2-alpine3.19
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: stock-market
    ports:
      - "5432:5432"
    networks:
      - local-network

  pgadmin:
    image: dpage/pgadmin4:7.4
    restart: always
    ports:
      - "8100:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - local-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.7
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - local-network

  broker:
    image: confluentinc/cp-kafka:7.2.7
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"  # Disable auto topic creation
    networks:
      - local-network

  stock-market:
    container_name: stock-market
    image: stock-market
    restart: always
    depends_on:
      - zookeeper
      - broker
    ports:
      - "8080:8080"
    networks:
      - local-network

networks:
  local-network:
    driver: bridge
