spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/stock-market?serverTimezone=UTC
    username: admin
    password: admin
  kafka:
    bootstrap-servers: localhost:29092
    schema.registry.url: http://localhost:8091
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.streams.serdes.avro.GenericAvroSerializer
      properties:
        schema.registry.url: ${spring.kafka.schema.registry.url}
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.streams.serdes.avro.GenericAvroDeserializer
      properties:
        schema.registry.url: ${spring.kafka.schema.registry.url}