spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:postgresql://postgres:5432/stock-market?serverTimezone=UTC
    username: admin
    password: admin
  liquibase:
    change-log: classpath:/liquibase/master.xml
  jackson:
    time-zone: UTC
  kafka:
    bootstrap-servers: broker:9092