/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.khalanirek.stockmarket.avro.investmentportfolio;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class InvestmentPortfolioCreatedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2147836705214223131L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"InvestmentPortfolioCreatedEvent\",\"namespace\":\"com.khalanirek.stockmarket.avro.investmentportfolio\",\"fields\":[{\"name\":\"investmentPortfolioId\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<InvestmentPortfolioCreatedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<InvestmentPortfolioCreatedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<InvestmentPortfolioCreatedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<InvestmentPortfolioCreatedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<InvestmentPortfolioCreatedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this InvestmentPortfolioCreatedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a InvestmentPortfolioCreatedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a InvestmentPortfolioCreatedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static InvestmentPortfolioCreatedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence investmentPortfolioId;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public InvestmentPortfolioCreatedEvent() {}

  /**
   * All-args constructor.
   * @param investmentPortfolioId The new value for investmentPortfolioId
   */
  public InvestmentPortfolioCreatedEvent(java.lang.CharSequence investmentPortfolioId) {
    this.investmentPortfolioId = investmentPortfolioId;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return investmentPortfolioId;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: investmentPortfolioId = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'investmentPortfolioId' field.
   * @return The value of the 'investmentPortfolioId' field.
   */
  public java.lang.CharSequence getInvestmentPortfolioId() {
    return investmentPortfolioId;
  }


  /**
   * Sets the value of the 'investmentPortfolioId' field.
   * @param value the value to set.
   */
  public void setInvestmentPortfolioId(java.lang.CharSequence value) {
    this.investmentPortfolioId = value;
  }

  /**
   * Creates a new InvestmentPortfolioCreatedEvent RecordBuilder.
   * @return A new InvestmentPortfolioCreatedEvent RecordBuilder
   */
  public static com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder newBuilder() {
    return new com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder();
  }

  /**
   * Creates a new InvestmentPortfolioCreatedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new InvestmentPortfolioCreatedEvent RecordBuilder
   */
  public static com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder newBuilder(com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder other) {
    if (other == null) {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder();
    } else {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder(other);
    }
  }

  /**
   * Creates a new InvestmentPortfolioCreatedEvent RecordBuilder by copying an existing InvestmentPortfolioCreatedEvent instance.
   * @param other The existing instance to copy.
   * @return A new InvestmentPortfolioCreatedEvent RecordBuilder
   */
  public static com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder newBuilder(com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent other) {
    if (other == null) {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder();
    } else {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for InvestmentPortfolioCreatedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<InvestmentPortfolioCreatedEvent>
    implements org.apache.avro.data.RecordBuilder<InvestmentPortfolioCreatedEvent> {

    private java.lang.CharSequence investmentPortfolioId;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.investmentPortfolioId)) {
        this.investmentPortfolioId = data().deepCopy(fields()[0].schema(), other.investmentPortfolioId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing InvestmentPortfolioCreatedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.investmentPortfolioId)) {
        this.investmentPortfolioId = data().deepCopy(fields()[0].schema(), other.investmentPortfolioId);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'investmentPortfolioId' field.
      * @return The value.
      */
    public java.lang.CharSequence getInvestmentPortfolioId() {
      return investmentPortfolioId;
    }


    /**
      * Sets the value of the 'investmentPortfolioId' field.
      * @param value The value of 'investmentPortfolioId'.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder setInvestmentPortfolioId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.investmentPortfolioId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'investmentPortfolioId' field has been set.
      * @return True if the 'investmentPortfolioId' field has been set, false otherwise.
      */
    public boolean hasInvestmentPortfolioId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'investmentPortfolioId' field.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.InvestmentPortfolioCreatedEvent.Builder clearInvestmentPortfolioId() {
      investmentPortfolioId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public InvestmentPortfolioCreatedEvent build() {
      try {
        InvestmentPortfolioCreatedEvent record = new InvestmentPortfolioCreatedEvent();
        record.investmentPortfolioId = fieldSetFlags()[0] ? this.investmentPortfolioId : (java.lang.CharSequence) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<InvestmentPortfolioCreatedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<InvestmentPortfolioCreatedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<InvestmentPortfolioCreatedEvent>
    READER$ = (org.apache.avro.io.DatumReader<InvestmentPortfolioCreatedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.investmentPortfolioId);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.investmentPortfolioId = in.readString(this.investmentPortfolioId instanceof Utf8 ? (Utf8)this.investmentPortfolioId : null);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.investmentPortfolioId = in.readString(this.investmentPortfolioId instanceof Utf8 ? (Utf8)this.investmentPortfolioId : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










