/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.khalanirek.stockmarket.avro.investmentportfolio;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class ShareBlockedEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5882471220506519804L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ShareBlockedEvent\",\"namespace\":\"com.khalanirek.stockmarket.avro.investmentportfolio\",\"fields\":[{\"name\":\"investmentPortfolioId\",\"type\":\"string\"},{\"name\":\"companyId\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"long\"},{\"name\":\"expirationTime\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ShareBlockedEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ShareBlockedEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ShareBlockedEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ShareBlockedEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ShareBlockedEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ShareBlockedEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ShareBlockedEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ShareBlockedEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ShareBlockedEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence investmentPortfolioId;
  private java.lang.CharSequence companyId;
  private long quantity;
  private java.lang.CharSequence expirationTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ShareBlockedEvent() {}

  /**
   * All-args constructor.
   * @param investmentPortfolioId The new value for investmentPortfolioId
   * @param companyId The new value for companyId
   * @param quantity The new value for quantity
   * @param expirationTime The new value for expirationTime
   */
  public ShareBlockedEvent(java.lang.CharSequence investmentPortfolioId, java.lang.CharSequence companyId, java.lang.Long quantity, java.lang.CharSequence expirationTime) {
    this.investmentPortfolioId = investmentPortfolioId;
    this.companyId = companyId;
    this.quantity = quantity;
    this.expirationTime = expirationTime;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return investmentPortfolioId;
    case 1: return companyId;
    case 2: return quantity;
    case 3: return expirationTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: investmentPortfolioId = (java.lang.CharSequence)value$; break;
    case 1: companyId = (java.lang.CharSequence)value$; break;
    case 2: quantity = (java.lang.Long)value$; break;
    case 3: expirationTime = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'investmentPortfolioId' field.
   * @return The value of the 'investmentPortfolioId' field.
   */
  public java.lang.CharSequence getInvestmentPortfolioId() {
    return investmentPortfolioId;
  }


  /**
   * Sets the value of the 'investmentPortfolioId' field.
   * @param value the value to set.
   */
  public void setInvestmentPortfolioId(java.lang.CharSequence value) {
    this.investmentPortfolioId = value;
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public java.lang.CharSequence getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(java.lang.CharSequence value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public long getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(long value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'expirationTime' field.
   * @return The value of the 'expirationTime' field.
   */
  public java.lang.CharSequence getExpirationTime() {
    return expirationTime;
  }


  /**
   * Sets the value of the 'expirationTime' field.
   * @param value the value to set.
   */
  public void setExpirationTime(java.lang.CharSequence value) {
    this.expirationTime = value;
  }

  /**
   * Creates a new ShareBlockedEvent RecordBuilder.
   * @return A new ShareBlockedEvent RecordBuilder
   */
  public static com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder newBuilder() {
    return new com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder();
  }

  /**
   * Creates a new ShareBlockedEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ShareBlockedEvent RecordBuilder
   */
  public static com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder newBuilder(com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder other) {
    if (other == null) {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder();
    } else {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder(other);
    }
  }

  /**
   * Creates a new ShareBlockedEvent RecordBuilder by copying an existing ShareBlockedEvent instance.
   * @param other The existing instance to copy.
   * @return A new ShareBlockedEvent RecordBuilder
   */
  public static com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder newBuilder(com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent other) {
    if (other == null) {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder();
    } else {
      return new com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ShareBlockedEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ShareBlockedEvent>
    implements org.apache.avro.data.RecordBuilder<ShareBlockedEvent> {

    private java.lang.CharSequence investmentPortfolioId;
    private java.lang.CharSequence companyId;
    private long quantity;
    private java.lang.CharSequence expirationTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.investmentPortfolioId)) {
        this.investmentPortfolioId = data().deepCopy(fields()[0].schema(), other.investmentPortfolioId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.companyId)) {
        this.companyId = data().deepCopy(fields()[1].schema(), other.companyId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.expirationTime)) {
        this.expirationTime = data().deepCopy(fields()[3].schema(), other.expirationTime);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing ShareBlockedEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.investmentPortfolioId)) {
        this.investmentPortfolioId = data().deepCopy(fields()[0].schema(), other.investmentPortfolioId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.companyId)) {
        this.companyId = data().deepCopy(fields()[1].schema(), other.companyId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.quantity)) {
        this.quantity = data().deepCopy(fields()[2].schema(), other.quantity);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.expirationTime)) {
        this.expirationTime = data().deepCopy(fields()[3].schema(), other.expirationTime);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'investmentPortfolioId' field.
      * @return The value.
      */
    public java.lang.CharSequence getInvestmentPortfolioId() {
      return investmentPortfolioId;
    }


    /**
      * Sets the value of the 'investmentPortfolioId' field.
      * @param value The value of 'investmentPortfolioId'.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder setInvestmentPortfolioId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.investmentPortfolioId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'investmentPortfolioId' field has been set.
      * @return True if the 'investmentPortfolioId' field has been set, false otherwise.
      */
    public boolean hasInvestmentPortfolioId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'investmentPortfolioId' field.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder clearInvestmentPortfolioId() {
      investmentPortfolioId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder setCompanyId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.companyId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder clearCompanyId() {
      companyId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public long getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder setQuantity(long value) {
      validate(fields()[2], value);
      this.quantity = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder clearQuantity() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'expirationTime' field.
      * @return The value.
      */
    public java.lang.CharSequence getExpirationTime() {
      return expirationTime;
    }


    /**
      * Sets the value of the 'expirationTime' field.
      * @param value The value of 'expirationTime'.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder setExpirationTime(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.expirationTime = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'expirationTime' field has been set.
      * @return True if the 'expirationTime' field has been set, false otherwise.
      */
    public boolean hasExpirationTime() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'expirationTime' field.
      * @return This builder.
      */
    public com.khalanirek.stockmarket.avro.investmentportfolio.ShareBlockedEvent.Builder clearExpirationTime() {
      expirationTime = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ShareBlockedEvent build() {
      try {
        ShareBlockedEvent record = new ShareBlockedEvent();
        record.investmentPortfolioId = fieldSetFlags()[0] ? this.investmentPortfolioId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.companyId = fieldSetFlags()[1] ? this.companyId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.quantity = fieldSetFlags()[2] ? this.quantity : (java.lang.Long) defaultValue(fields()[2]);
        record.expirationTime = fieldSetFlags()[3] ? this.expirationTime : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ShareBlockedEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ShareBlockedEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ShareBlockedEvent>
    READER$ = (org.apache.avro.io.DatumReader<ShareBlockedEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.investmentPortfolioId);

    out.writeString(this.companyId);

    out.writeLong(this.quantity);

    out.writeString(this.expirationTime);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.investmentPortfolioId = in.readString(this.investmentPortfolioId instanceof Utf8 ? (Utf8)this.investmentPortfolioId : null);

      this.companyId = in.readString(this.companyId instanceof Utf8 ? (Utf8)this.companyId : null);

      this.quantity = in.readLong();

      this.expirationTime = in.readString(this.expirationTime instanceof Utf8 ? (Utf8)this.expirationTime : null);

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.investmentPortfolioId = in.readString(this.investmentPortfolioId instanceof Utf8 ? (Utf8)this.investmentPortfolioId : null);
          break;

        case 1:
          this.companyId = in.readString(this.companyId instanceof Utf8 ? (Utf8)this.companyId : null);
          break;

        case 2:
          this.quantity = in.readLong();
          break;

        case 3:
          this.expirationTime = in.readString(this.expirationTime instanceof Utf8 ? (Utf8)this.expirationTime : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










